# Generated by Django 5.1.6 on 2025-02-23 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='restaurante',
            new_name='Platillos',
        ),
    ]
