# Generated by Django 5.1.6 on 2025-03-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
