# Generated by Django 5.1.6 on 2025-03-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0004_platillos_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillos',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
