# Generated by Django 5.1.6 on 2025-03-11 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0005_alter_platillos_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('codigo_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('identificacion_persona', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_platillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.platillos')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='restaurante.pedido')),
            ],
        ),
    ]
