# Generated by Django 5.1.6 on 2025-03-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0006_remove_platillos_platillo_platillos_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillos',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
